apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-hello-world
  namespace: hello-world  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-hello-world
  template:
    metadata:
      labels:
        app: app-hello-world
    spec:
      containers:
      - name: hello-world
        image: mcr.microsoft.com/azuredocs/aks-helloworld:v1
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
          requests:
            cpu: 150m
            memory: 150Mi
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
            httpGet:
              path: /
              port: http
        readinessProbe:
            httpGet:
              path: /
              port: http
        env:
        - name: TITLE
          value: "Welcome to Azure Arc-enabled Kubernetes cluster and MVP-Dagen!"