apiVersion: v1
kind: Service
metadata:
  name: svc-hello-world
  namespace: hello-world
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: app-hello-world