apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: "dev"
resources:
  - ../../../apps/hello-world
replicas:
  - name: deploy-hello-world
    count: 3
replacements:
- source:
    fieldPath: spec.clusterIP
    kind: Service
    name: svc-hello-world
    namespace: hello-world
  targets:
  - fieldPaths:
    - spec.template.spec.containers.[name=hello-world].env.[name=TEST].value
    select:
      kind: Deployment
      name: deploy-hello-world
      namespace: hello-world